name: Perks
version: '${project.version}'
main: com.lupino.perks.Perks
api-version: '1.20'
commands:
  perks:
    description: Opens perk menu
    aliases: perk
  setpoints:
    description: Set points for a player.
    permission: op
  points:
    description: Check the points of a player.
