# Most numbers specified here by default will be set if no value is specified in the configuration.

# Pointsperkill - The number of points awarded per kill.
Pointsperkill: 1

# Enabling perks in individual worlds.
EnablePerksInEnd: true
EnablePerksInOverworld: true
EnablePerksInNether: true

# The safe zone is an area where perks are disabled. One safe zone can be created per world.
# loc1 represents one corner, and loc2 represents the opposite corner. x, y, and z are the coordinates of the respective corners.
# If the world's name is different, it is necessary to include the world name with loc1 and loc2.

Safezone:
  # Two corners in the overworld
  Overworld:
    loc1:
      ==: org.bukkit.Location
      world: world
      x: -304
      y: 125
      z: -733
    loc2:
      ==: org.bukkit.Location
      world: world
      x: -234
      y: 75
      z: -803
  # Two corners in the nether
  Nether:
    loc1:
      ==: org.bukkit.Location
      world: world_nether
      x: 0
      y: 0
      z: 0
    loc2:
      ==: org.bukkit.Location
      world: world_nether
      x: 0
      y: 0
      z: 0
  # Two corners in the end
  End:
    loc1:
      ==: org.bukkit.Location
      world: world_the_end
      x: 0
      y: 0
      z: 0
    loc2:
      ==: org.bukkit.Location
      world: world_the_end
      x: 0
      y: 0
      z: 0

# Shop - Determines whether an item can be purchased in the shop.
# Price - Cost in points.
# Usages - The number of uses available.
# Cooldown - Cooldown in seconds.
# Powerofeffect - The strength of the potion effect.
# Duration - Duration of the potion effect in seconds.
# Powerofpush - Boost strength; a value of 2 corresponds to approximately 20 blocks upward.
# Damage - Damage dealt, measured in HP.
# You can add as many lines of lore as you want to any item. Each new line starts with - "text". If you include a line with just - "", it will create a blank line in the lore, adding a visual gap.

Scout:
  Shop: true
  Price: 10
  Usages: 5
  Cooldown: 60
  Powerofpush: 2.5
  Lore:
    - ""
    - "&fPřitáhně tě na místo,"
    - "&fkde nahodíš."

Jumper:
  Shop: true
  Price: 10
  Usages: 5
  Cooldown: 60
  Powerofpush: 2
  Lore:
    - ""
    - "&fBoostne tě dopředu."


Runner:
  Shop: true
  Price: 10
  Usages: 5
  Cooldown: 120
  Duration: 10
  Powerofeffect: 4
  Lore:
    - ""
    - "&fSpeed 4 na 10 s."

Miner:
  Shop: true
  Price: 10
  Usages: 10
  Cooldown: 60
  Duration: 30
  Powerofeffect: 3
  Lore:
    - ""
    - "&fHaste 3 na 30 s."

Knight:
  Shop: true
  Price: 10
  Usages: 5
  Cooldown: 60
  Duration: 10
  Powerofeffect: 4
  Lore:
    - ""
    - "&fStrenght 4 na 10 s."

Thor:
  Shop: false
  Price: 10
  Usages: 10
  Cooldown: 60
  Damage: 30
  Lore:
    - ""
    - "&fBleskovací tyčka."

Tank:
  Shop: true
  Price: 10
  Usages: 5
  Cooldown: 60
  Duration: 10
  Powerofeffect: 4
  Lore:
    - ""
    - "&fResistance 4 na 10 s."
